### PR TITLE
Visual update of the Mycenae buildings

### PR DESCRIPTION
**Pull request by niektb**
What needs to be done after committing is checking the UV of the Fortress (since it has a weird seem)
Also new AO's can be baked from the other buildings.

### CODE REVIEW

**Comment by s0600204** [comment]
The placement of the tree props on the `civic_center` and `storehouse` structures seems... a little off... http://imgur.com/a/s3nHr

**Comment by niektb** [comment]
Stan and I talked about that yesterday and it is caused the fact that LordGood used an older version of blender. If you would import the .dae into a newer version of Blender the attachpoint locations are lost.

**Comment by s0600204** [comment]
Ah, my apologies, I've been busy with work and so haven't been keeping an eye on the IRC logs. As long as someone's aware...

**Comment by niektb** [comment]
Yeah, it's better that it gets noticed twice than not at all :)

**Pull request merged**
